# Generated by Django 5.1 on 2024-08-29 20:19

import django.db.models.deletion
import mybackend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[mybackend.validators.validate_rut])),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[mybackend.validators.validate_rut])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='api.empresa')),
            ],
        ),
    ]
